[tools]
node = "20.5.0"
npm = "9.8.0"

[env]
# SERVER
PORT=3000

# DOCKER
WORKDIR="/usr/src/app/"

# STORAGE
FILES_LOCATION="./data"

# INFLUX
# If you want to use docker for your InfluxDB instance, uncomment these lines.
INFLUX_HOST="aggr-influx" # or `aggr-influx` if used in Docker
INFLUX_PORT="8086"

# WEB PUSH API KEYS - Copy Public key in Aggr .env
PRIVATE_VAPID_KEY="BNi_5_w2FU8LdTg5KxQvHYi0hXzyKMIYmYXin1nUyXEtXfyAAef0pe68v3hrQwDP00NPGPasGTrurB8Hmi3On7I"
PUBLIC_VAPID_KEY="BNi_5_w2FU8LdTg5KxQvHYi0hXzyKMIYmYXin1nUyXEtXfyAAef0pe68v3hrQwDP00NPGPasGTrurB8Hmi3On7I"